
# -name: nice
#   gender: nan



 server:
   port: 80

 rocketmq:
   name-server: localhost:9876
   producer:
     group: group_rocketmq


#  myrocketmq-config:
#    my-topic: TestTopic
#    my-consumer-group: group_rocketmq
